# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Yueba' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Yueba
pod 'AFNetworking', '~> 3.1.0'
pod 'SVProgressHUD', '~> 2.0.3'
pod 'SWRevealViewController', '~> 2.3.0'
pod 'BaiduMapKit' #百度地图SDK
end
